name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.1'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ gcc

      - name: Insert missing include
        run: sed -i '1i#include <limits>' /home/runner/work/vis_assign/vis_assign/src/robot_controller_ui.cc

      - name: Configure and Build
        run: |
          cmake -B build -S .
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/
