name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.1'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure and Build
        run: |
          cmake -B build -S .
          echo 'set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=maybe-uninitialized")' >> CMakeLists.txt
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ./test/assignment_test

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/
